#############################################################################
## Description: This is a deployment creation for 
## mongo-db  Deployment and internal service for 
## connection establishment
##
## CREATED BY: YADNESH PURAV
## CREATION DATE: 06 OCTOBER 2024
##
##  VERSION      DATE        AUTHOR      UPDATE
#############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret 
              key: mongo-root-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password 


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-db
  ports:
  - port: 80
    targetPort: 27017

