#############################################################################
## Description: This is a deployment creation for 
## mongo-express  Deployment and exernal service for 
## connecting to internal db and for external users
##
## CREATED BY: YADNESH PURAV
## CREATION DATE: 06 OCTOBER 2024
##
##  VERSION      DATE        AUTHOR      UPDATE
#############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      name: mongo-express
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express-container
        image: mongo-express
        ports: 
        - containerPort: 8081
        env:
        - name:  ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: db-url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - port: 8080
    targetPort: 8081
    nodePort: 30001

