#############################################################################
## Description: This is a simple Dockerfile which is  
## used to build the nginx image with our html file 
## for the web page
##
## CREATED BY: YADNESH PURAV
## CREATION DATE: 26 SEPTEMBER 2024
#############################################################################
FROM nginx
COPY *.html /usr/share/nginx/html/
