apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-app
    type: web-page
spec:
  containers:
  - name: my-nginx-webapp
    image: yadup007/project_repo:my-nginx-webapp.v83 
 
