#############################################################################
## Description: This is a yaml file for nginx-web app service
## creation to get access to the web page created through URL
## 
##
## CREATED BY: YADNESH PURAV
## CREATION DATE: 01 OCTOBER 2024
#############################################################################
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports: 
  - targetPort: 80
    port: 8080
    nodePort: 30000
  selector:
    app: my-app

